### ISSUE TITLE
PC algorithm and Meek rules

### ISSUE THREAD

**Issue by kenneth-lee-ch** [py-why/causal-learn#93] opened 2023-01-31 07:53 UTC
I generate some sample data and use the PC algorithm to get an essential graph. but when I plot the graph. It looks like this. 

I have several questions.

1. Why there is no arrow from X8 -> X9 in this case, shouldn't Meek rules be able to orient X8-X9 as X8->X9?
2. What is the difference between `Meek.meek` and `Meek.definite_meek()`?
3. If I want to orient a DAG with Meek rules after I manually change some orientations of the graph. How should I go about it?

![Screenshot 2023-01-31 at 2 51 16 AM](https://user-images.githubusercontent.com/24616330/215698926-722774d3-3bcd-4db3-83c1-2a7a6c2fabc4.png)

Thank you for having a look at this thread.

**Comment by MarkDana** [comment] 2023-02-01 08:33
Hi @kenneth-lee-ch! Thanks for reaching out! Could you please provide us with a code snippet and data to reproduce this result? I'll have a look this weekend :)

**Comment by zhi-yi-huang** [comment] 2023-02-01 09:28
This is probably a bug caused by [`generalgraph.py`](https://github.com/py-why/causal-learn/blob/ddac4d92a1759afaea6218f0f68b43c8973af1a5/causallearn/graph/GeneralGraph.py), which has been fixed in [3cfd99e](https://github.com/py-why/causal-learn/pull/68/commits/3cfd99ed132ef671654df7ed2b1806aca469da6e). Perhaps you could try to use this version of the code. If there is any problem, please let us know. Thanks!

**Comment by kenneth-lee-ch** [comment] 2023-02-01 14:26
My causal-learn version is `0.1.3.1`. Below is the script I used:

```
import pyAgrum as gum
num_nodes = 15
graphnames = ['X' + str(i) for i in range(num_nodes)]
sample_size = 10000
bn = gum.randomBN(n=num_nodes, names=graphnames) 
# sample from the data
filepath = "data/tr_data.csv"
gum.generateSample(bn, sample_size, name_out=filepath)

df = pd.read_csv(filepath)
cg = pc(df.to_numpy())

# plot it right below
cg.draw_pydot_graph(labels=list(df.columns))
```

**Comment by kunwuz** [comment] 2023-02-01 17:40
Hi @kenneth-lee-ch, many thanks for your script. The updated code is in a [PR](https://github.com/py-why/causal-learn/pull/68) that is still in its final reviewing stage. I tried your script with the updated code and it works fine, but randomBN(.) generated a different graph on my side. We will let you know once that PR is merged. At the same time, if you would like to, you could try building the [source with the updated code](https://github.com/zhi-yi-huang/causal-learn) and then we hope the issue could be solved.

**Comment by kenneth-lee-ch** [comment] 2023-02-01 18:00
@kunwuz thanks! I will try it out.

**Comment by kenneth-lee-ch** [comment] 2023-02-02 04:04
I have a follow-up question. If I want to run Meek rules on a graph that has some undirected edges and directed edges. How should I proceed? Should I use`Meek.meek` or `Meek.definite_meek`? What is the difference?

**Comment by kunwuz** [comment] 2023-02-09 19:51
Perhaps you could try to manually initialize a graph with specified nodes and edges and then do the meek orientation. These parts of the code might be helpful (thanks to @zhi-yi-huang !): (1)[https://github.com/py-why/causal-learn/blob/main/causallearn/search/ConstraintBased/PC.py#L221-L244](https://github.com/py-why/causal-learn/blob/main/causallearn/search/ConstraintBased/PC.py#L221-L244)  (2) [https://github.com/py-why/causal-learn/blob/main/tests/TestBackgroundKnowledge.py](https://github.com/py-why/causal-learn/blob/main/tests/TestBackgroundKnowledge.py).

For the difference between Meek.meek or Meek.definite_meek, this [paper](https://arxiv.org/ftp/arxiv/papers/1610/1610.00378.pdf) might be helpful. When we set the 'uc_rule' to 2, we orient only the definite colliders in the skeleton and keep track of all the definite non-colliders as well, as described [here](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Constraint-based%20causal%20discovery%20methods/PC.html).

BTW, the newest version has been updated on the pypi, so please feel free to update it via pip and try it out :)

**Comment by kenneth-lee-ch** [comment] 2023-02-09 20:02
Thanks a lot! I have no more questions.

**Comment by kunwuz** [comment] 2023-02-11 07:51
Thanks so much! Free feel to reopen it if there are any questions.

**Closed by kunwuz** 2023-02-11 07:51 UTC
